apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-html-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
      - name: app-html
        image: httpd:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
--- 
apiVersion: v1
kind: Service
metadata:
  name: app-html
spec:
  selector:
    app: app-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
